[project]
name = "2048-clean-architecture"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
]

[tool.mypy]
strict = true

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
